version: "3.4"

x-common-variables:
  &db-env-vars
    POSTGRES_DB: anime
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    PORT_API: 8080
    PORT_DEBUG: 5005
    POSTGRES_DB_URL: r2dbc:pool:postgresql://db-compose:5432/anime
#    DB_URL: r2dbc:pool:postgresql://db-compose:5432/${POSTGRES_DB}
    #r2dbc:<driver>://<host>:<port>/<database>

volumes:
  webflux_data:

networks:
  webflux_rede:

services:
  db-compose:
    container_name: db-compose
    image: postgres:9.5-alpine
    hostname: postgres # postgres hostname
    restart: always
    ports:
      - 5432:5432
    volumes:
      - webflux_data:/var/lib/postgresql/data
    networks:
      - webflux_rede
    environment:
      *db-env-vars

  web-api:
    image: pauloportfolio/web-api
    build:
      context: ./
      dockerfile: ./dev-dockerfile
      args:
        JAR_FILE: target/spring-webflux-essentials-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - webflux_data:/var/lib/mysql/data
    depends_on:
      - db-compose
    networks:
      - webflux_rede
    environment:
      PROFILE: dev
      <<: *db-env-vars
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      #JDK>=09: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      #JDK  08: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m

#POSTGRES - CHANGED FOR MYSQL, BECAUSE THE PASSWORD IN POSTGRES DOES NO ALLOW ENCRYPTATION
#      DB_URL: r2dbc:pool:postgresql://db-compose:5432/${POSTGRES_DB}



